# Generated by Django 3.1.5 on 2021-02-06 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grudapp', '0002_auto_20210206_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('add', 'add'), ('POST', 'POST')]},
        ),
    ]
