# Generated by Django 3.1.5 on 2021-02-06 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grudapp', '0003_auto_20210206_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('add', 'Make add')]},
        ),
    ]
