# Generated by Django 3.1.5 on 2021-02-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grudapp', '0005_auto_20210206_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('add', 'Can add'), ('change', 'Can put'), ('delete', 'Can remove '), ('a', 'add'), ('c', 'change'), ('d', 'delete')]},
        ),
    ]
